-- ========================
-- COUNTRY TABLE
-- ========================
create table country
(
    id        bigint generated by default as identity primary key,
    name      varchar(255),
    continent varchar(255)
);

-- ========================
-- USERS TABLE
-- ========================
create table users
(
    username                   varchar(255) primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

-- create index idx_reserved_accommodation (user_id);
create index idx_user_username_password on users (username, password);
create index idx_user_username on users (username);
create index idx_user_role on users (role);

-- ========================
-- HOST TABLE
-- ========================
create table host
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint references country
);

-- ========================
-- GUEST TABLE
-- ========================
create table guest
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    country_id bigint references country
);

-- ========================
-- HOST_GUESTS JOIN TABLE (Many-to-Many)
-- ========================
create table host_guests
(
    host_id  bigint references host on delete cascade,
    guest_id bigint references guest on delete cascade,
    primary key (host_id, guest_id)
);

-- ========================
-- ACCOMMODATION TABLE
-- ========================
create table accommodation
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    category   varchar(50), -- Enum as string
    host_id    bigint references host,
    numberOfRooms  integer,
    rented     boolean default false,
    user_id    varchar(255) references users
);